# Generated by Django 4.2.5 on 2024-06-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('available', models.BooleanField(default=False)),
                ('article', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('characteristics', models.JSONField(default=dict)),
                ('season', models.CharField(max_length=255)),
                ('guide', models.JSONField(default=dict)),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
