# Generated by Django 5.0 on 2024-06-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('image', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('image', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('available', models.BooleanField(default=False, verbose_name='Наявність')),
                ('article', models.CharField(max_length=255, verbose_name='Опис товару')),
                ('material', models.CharField(max_length=255, verbose_name='Матеріал')),
                ('country', models.CharField(max_length=255, verbose_name='Країна')),
                ('characteristics', models.JSONField(default=dict, verbose_name='Характеристики')),
                ('season', models.CharField(max_length=255, verbose_name='Сезон')),
                ('guide', models.JSONField(default=dict, verbose_name='Рекомендації щодо догляду')),
                ('description', models.TextField(verbose_name='Опис')),
                ('size', models.CharField(max_length=255, verbose_name='Розмір')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('color', models.CharField(max_length=255, verbose_name='Колір')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категорія')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
