# Generated by Django 4.2.5 on 2024-06-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='S', max_length=255),
        ),
    ]
